import {
  Home,
  Users,
  Fence,
  Sparkles,
  Flame,
  CalendarHeart,
  Trees,
  Footprints,
  Waves,
  PartyPopper,
  Wind,
  Droplet,
  WashingMachine,
  Refrigerator,
  BedDouble,
  Wifi,
  Disc3,
  Thermometer,
  ChefHat,
  Clock,
  Dog,
  CalendarRange,
  Volleyball,
  Dribbble,
  Goal,
  Table2,
  Feather,
  Circle,
  Dumbbell,
  Gamepad2,
  Baby,
  Bike,
  Car,
  Armchair,
  Dice5,
  Sailboat,
  Snowflake,
  Mic2,
  Cake,
  Heart,
  Briefcase,
  MessageSquare,
  CreditCard,
  RotateCcw,
  KeyRound,
  MessageCircle,
  Send,
  Share2,
  Instagram,
  Phone,
  Mail,
  MapPin,
  Star,
  Check,
  Bath,
  Tent,
  Music,
  Gift,
  Sun,
  HelpCircle,
  type LucideIcon,
} from 'lucide-react'

/**
 * Curated icon set. Content stores icon NAMES (strings) so a non-technical
 * admin can pick from a list; this map turns them into components at render
 * time. Unknown names fall back to `HelpCircle`.
 */
export const iconMap: Record<string, LucideIcon> = {
  Home,
  Users,
  Fence,
  Sparkles,
  Flame,
  CalendarHeart,
  Trees,
  Footprints,
  Waves,
  PartyPopper,
  Wind,
  Droplet,
  WashingMachine,
  Refrigerator,
  BedDouble,
  Wifi,
  Disc3,
  Thermometer,
  ChefHat,
  Clock,
  Dog,
  CalendarRange,
  Volleyball,
  Dribbble,
  Goal,
  Table2,
  Feather,
  Circle,
  Dumbbell,
  Gamepad2,
  Baby,
  Bike,
  Car,
  Armchair,
  Dice5,
  Sailboat,
  Snowflake,
  Mic2,
  Cake,
  Heart,
  Briefcase,
  MessageSquare,
  CreditCard,
  RotateCcw,
  KeyRound,
  MessageCircle,
  Send,
  Share2,
  Instagram,
  Phone,
  Mail,
  MapPin,
  Star,
  Check,
  Bath,
  Tent,
  Music,
  Gift,
  Sun,
  HelpCircle,
}

/** All icon names, for the admin IconPicker. */
export const iconNames: string[] = Object.keys(iconMap)

interface IconProps {
  name: string
  className?: string
  'aria-hidden'?: boolean
  strokeWidth?: number
}

/** Render a Lucide icon by name with a safe fallback. */
export function Icon({ name, className, strokeWidth = 1.75, ...rest }: IconProps) {
  const Cmp = iconMap[name] ?? HelpCircle
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden {...rest} />
}
